name: 'Dependency Review'

'on':
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Dependency Review
        uses: actions/dependency-review-action@v5
        with:
          # Fail on introduced vulnerabilities
          fail-on-severity: moderate

          # Fail on disallowed licenses (configurable list of prohibited SPDX identifiers)
          license-check: true
          deny-licenses: 'GPL-2.0, GPL-3.0, AGPL-3.0, LGPL-2.1, LGPL-3.0'

          # Post review summary as a comment on the pull request
          comment-summary-in-pr: always
